### ISSUE TITLE
list_pages() function returns an error

### ISSUE THREAD

**Issue by aakashb14** [microsoft/semantic-link-labs#730]
**What are you trying to achieve?**
I'm trying to use sempy library to get a list of pages in my report which is in PBIR format by using the list_pages() function. 

**What have you tried so far?**
I'm using the [Report Analysis.ipynb](https://github.com/microsoft/semantic-link-labs/wiki/Code-Examples) from Code Examples to try this out but getting an error - **AttributeError: 'str' object has no attribute 'get'**. I entered the report and workspace names in the parameters and ran the code to list pages in the report.

**Comment by m-kovalsky** [comment]
Please provide the full error in text and the code you executed

**Comment by aakashb14** [comment]
Hello,

Attached is the code executed and error message.

Thanks,
Aakash

**Comment by aakashb14** [comment]
Here is the code. Not sure if it got attached when I replied via email earlier. 

%pip install semantic-link-labs 0.10.1


import sempy_labs as labs
import sempy_labs.report as rep
from sempy_labs.report import ReportWrapper
from sempy_labs.report._reportwrapper import (
    ReportWrapper
)

# For checking reports
report_name = 'Accounts Payable - Composite (2)' # Enter the report name
report_workspace = 'Finance Analytics' # Enter the workspace in which the report exists
rpt = ReportWrapper(report=report_name, workspace=report_workspace)

rpt.list_pages()

**Comment by m-kovalsky** [comment]
I believe this is fixed in [0.11.0](https://github.com/microsoft/semantic-link-labs/releases/tag/0.11.0). Please confirm as I wasn't able to reproduce the error.

**Comment by aakashb14** [comment]
I tested this but the issue still persists. The error occurs only for thin reports (live connected reports) in PBIR format. The code works fine for a normal report which is in the same PBIP project as the semantic model. 

Steps to recreate - 
1. Publish a PBIP project to PBI service
2. Open PBI desktop, connect to the semantic model and create a sample report.
3. Save the report in PBIP format.
4. Publish to service and run the notebook code shared earlier.

Another observation is when I close PBI desktop and re-open the report in step 3, it throws an error. I've had to point it to the semantic model again by using transform data -> data source settings -> select the semantic model. I wonder if there's a bug in PBIR format and these two issues are related? Or if this is not how we're supposed to deal with live connected reports when using PBIP/PBIR formats and there's another recommended way.

**Comment by m-kovalsky** [comment]
Please share the full error message that you get now (using 0.11.1).

**Comment by aakashb14** [comment]
## Code

%pip install semantic-link-labs 0.11.1

import sempy_labs as labs
from sempy_labs.report import get_report_json
from sempy_labs.report import ReportWrapper
from sempy_labs.report._reportwrapper import (
ReportWrapper
)

report_name = 'Accounts Payable - Composite (2)' # Enter the report name
report_workspace = 'Finance Analytics' # Enter the workspace in which the report exists
rpt = ReportWrapper(report=report_name, workspace=report_workspace)

rpt.list_pages()


## Error Message

File ~/cluster-env/trident_env/lib/python3.10/site-packages/sempy_labs/report/_reportwrapper.py:953, in ReportWrapper.list_visual_objects.<locals>.find_entity_property_pairs(data, result, keys_path)
    951     for key, value in data.items():
    952         keys_path.append(key)
--> 953         find_entity_property_pairs(value, result, keys_path)
    955 elif isinstance(data, list):
    956     for item in data:

File ~/cluster-env/trident_env/lib/python3.10/site-packages/sempy_labs/report/_reportwrapper.py:957, in ReportWrapper.list_visual_objects.<locals>.find_entity_property_pairs(data, result, keys_path)
    955 elif isinstance(data, list):
    956     for item in data:
--> 957         find_entity_property_pairs(item, result, keys_path)
    959 return result

File ~/cluster-env/trident_env/lib/python3.10/site-packages/sempy_labs/report/_reportwrapper.py:953, in ReportWrapper.list_visual_objects.<locals>.find_entity_property_pairs(data, result, keys_path)
    951     for key, value in data.items():
    952         keys_path.append(key)
--> 953         find_entity_property_pairs(value, result, keys_path)
    955 elif isinstance(data, list):
    956     for item in data:

File ~/cluster-env/trident_env/lib/python3.10/site-packages/sempy_labs/report/_reportwrapper.py:953, in ReportWrapper.list_visual_objects.<locals>.find_entity_property_pairs(data, result, keys_path)
    951     for key, value in data.items():
    952         keys_path.append(key)
--> 953         find_entity_property_pairs(value, result, keys_path)
    955 elif isinstance(data, list):
    956     for item in data:

File ~/cluster-env/trident_env/lib/python3.10/site-packages/sempy_labs/report/_reportwrapper.py:928, in ReportWrapper.list_visual_objects.<locals>.find_entity_property_pairs(data, result, keys_path)
    924     keys_path = []
    926 if isinstance(data, dict):
    927     if (
--> 928         "Entity" in data.get("Expression", {}).get("SourceRef", {})
    929         and "Property" in data
    930     ):
    931         entity = (
    932             data.get("Expression", {})
    933             .get("SourceRef", {})
    934             .get("Entity", {})
    935         )
    936         property_value = data.get("Property", {})

AttributeError: 'str' object has no attribute 'get'

**Comment by m-kovalsky** [comment]
I'm not able to reproduce this error. Would you be able to email me the PBIR definition so I can investigate (mikova@microsoft.com)?

**Comment by aakashb14** [comment]
Hi Michael - I've emailed the PBIR definition.

**Comment by aakashb14** [comment]
I uninstalled the older semantic link labs packages and reinstalled the 0.11.2 version and this is working now. Looks like the package wasn't getting updated to 0.11.1 when I tried it few weeks ago. Removing it altogether and reinstalling did the trick though.
