### ISSUE TITLE
Functions using deltalake.DeltaTable break on LH shortcuts to WH tables

### ISSUE THREAD

**Issue by philosophicles** [microsoft/semantic-link-labs#886]
**Describe the bug**

Certain functions in sempy_labs.lakehouse cannot handle lakehouses containing shortcuts to warehouse tables. The problem occurs where the `deltalake.DeltaTable` class is used internally (for pure-python notebooks).

I've found these affected functions:

1. get_lakehouse_tables _(only if the `extended` or `count_rows` flags are set)_
2. get_lakehouse_columns
3. optimize_lakehouse_tables _(affected via `optimize_table()` call, not via earlier call to get_lakehouse_tables())_
4. vacuum_lakehouse_tables _(again, affected via internal `vacuum_table()` call)_

I am not 100% sure if there are others affected as well.

**To Reproduce**

1. Create a warehouse with a table in it
2. Create a lakehouse in the same workspace with a shortcut to the warehouse table
3. In a pure-python notebook, call one of the above functions, referencing this lakehouse either explicitly or implicitly (and not referencing specific tables, where that's an option). 

Error will be raised from the deltalake package:

> DeltaError: Generic DeltaTable error: missing-column: createdTime

By comparison, if the lakehouse only includes shortcuts to other lakehouse tables, or does not include any shortcuts, this error isn't encountered.

**Expected behavior**

I don't think the deltalake package is doing anything wrong here; I can't imagine it's meant to work on Fabric Warehouse delta tables, since the Fabric WH engine expects to solely manage them and allow interaction only via the WH SQL endpoint.

I think the sempy-labs functions should either:

* detect if a LH table is a shortcut to a warehouse and if so, skip the relevant bit of code; or
* catch the `DeltaError` if raised and continue gracefully.

In either case, any relevant outputs (such as pandas dfs) can show a None/null/empty kind of value for these cases. For the `get_` functions, it may help to add an extra boolean field to dataframe outputs that explicitly indicates "this row relates to a shortcut to a warehouse table". Then client code can choose how to handle that data.

I do not think any python exception needs to be raised back to the client code in such cases; WH tables cannot be optimised or vacuumed on demand (AFAIK), and I don't think it's unreasonable to return less-complete results from the `get_` functions in this situation.

**Comment by philosophicles** [comment]
Just wanted to observe that the implementation of #888 that is coming together would mean shortcuts are _never_ in-scope for the optimize function, and probably not the vacuum function either. Thus resolving this bug for those two functions.

get_lakehouse_tables() and get_lakehouse_columns() would still be affected by this bug, though.

**Comment by m-kovalsky** [comment]
Just wanted to check if this is still an issue.

**Comment by philosophicles** [comment]
Thanks for checking in. Have just retested on SLL 0.13.1.

* optimize_lakehouse_tables() and vacuum_lakehouse_tables() are WORKING thanks to #888
* get_lakehouse_columns() is WORKING (presumably not part of #888)
* get_lakehouse_tables() still has problems, though it is no longer the `DeltaError` being raised that I originally described. I'm not sure if it's a related error still, or entirely unrelated. I will put more details into a separate comment shortly - let me know if you think I should reraise some or all of this as a new issue.

**Comment by m-kovalsky** [comment]
Please share the code executed and the full error message in text.

**Comment by philosophicles** [comment]
OK firstly here's a summary of what I've tried: I think this becomes pretty clear that it's a different bug to the one I created this issue for.

<img width="894" height="528" alt="Image" src="https://github.com/user-attachments/assets/613ebc4a-a39e-4247-9320-d2f2e39498b8" />

I appreciate it's not completely exhaustive of all the possible combinations but it feels like there's a general regression involving the `count_rows`-specific code path, and a separate regression involving the `extended`-specific code path. Neither is dependent on shortcuts to warehouse tables specifically.

# My code

````
!pip install --upgrade semantic-link-labs
!pip show semantic-link-labs # verify version
from sempy_labs import lakehouse as l

# then variations on the following, each in a separate code cell, with the different function params described in the screenshot
# I just hardcoded names of lakehouses all in the same sandbox workspace as the notebook I was using to test. 

l.get_lakehouse_tables('empty_lakehouse_with_schemas')
````

Here's the variations of calls from the screenshot for copy-pasting: 

````
l.get_lakehouse_tables('lh_name')
l.get_lakehouse_tables('lh_name', extended=True)
l.get_lakehouse_tables('lh_name', extended=True, exclude_shortcuts=True)
l.get_lakehouse_tables('lh_name', count_rows=True)
l.get_lakehouse_tables('lh_name', count_rows=True, exclude_shortcuts=True)
````

# Error message 1 (pandas KeyError)

````
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/jupyter-env/python3.11/lib/python3.11/site-packages/pandas/core/indexes/base.py:3791, in Index.get_loc(self, key)
   3790 try:
-> 3791     return self._engine.get_loc(casted_key)
   3792 except KeyError as err:

File index.pyx:152, in pandas._libs.index.IndexEngine.get_loc()

File index.pyx:181, in pandas._libs.index.IndexEngine.get_loc()

File pandas/_libs/hashtable_class_helper.pxi:7080, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas/_libs/hashtable_class_helper.pxi:7088, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'Row Count'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Cell In[10], line 1
----> 1 l.get_lakehouse_tables('empty_lakehouse_with_schemas', count_rows=True)

File ~/jupyter-env/python3.11/lib/python3.11/site-packages/sempy/_utils/_log.py:370, in mds_log.<locals>.get_wrapper.<locals>.log_decorator_wrapper(*args, **kwargs)
    367 start_time = time.perf_counter()
    369 try:
--> 370     result = func(*args, **kwargs)
    372     # The invocation for get_message_dict moves after the function
    373     # so it can access the state after the method call
    374     message.update(extractor.get_completion_message_dict(result, arg_dict))

File ~/jupyter-env/python3.11/lib/python3.11/site-packages/sempy_labs/lakehouse/_get_lakehouse_tables.py:180, in get_lakehouse_tables(lakehouse, workspace, extended, count_rows, export, exclude_shortcuts)
    178     df["Row Group Guardrail Hit"] = df["Row Groups"] > df["Row Group Guardrail"]
    179 if count_rows:
--> 180     df["Row Count"] = df["Row Count"].astype(int)
    181     df["Row Count Guardrail Hit"] = df["Row Count"] > df["Row Count Guardrail"]
    183 if exclude_shortcuts:

File ~/jupyter-env/python3.11/lib/python3.11/site-packages/pandas/core/frame.py:3893, in DataFrame.__getitem__(self, key)
   3891 if self.columns.nlevels > 1:
   3892     return self._getitem_multilevel(key)
-> 3893 indexer = self.columns.get_loc(key)
   3894 if is_integer(indexer):
   3895     indexer = [indexer]

File ~/jupyter-env/python3.11/lib/python3.11/site-packages/pandas/core/indexes/base.py:3798, in Index.get_loc(self, key)
   3793     if isinstance(casted_key, slice) or (
   3794         isinstance(casted_key, abc.Iterable)
   3795         and any(isinstance(x, slice) for x in casted_key)
   3796     ):
   3797         raise InvalidIndexError(key)
-> 3798     raise KeyError(key) from err
   3799 except TypeError:
   3800     # If we have a listlike key, _check_indexing_error will raise
   3801     #  InvalidIndexError. Otherwise we fall through and re-raise
   3802     #  the TypeError.
   3803     self._check_indexing_error(key)

KeyError: 'Row Count'
````


# Error message 2 (os join() TypeError)

````
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[13], line 1
----> 1 l.get_lakehouse_tables('Test_fastcp_LH', extended=True)

File ~/jupyter-env/python3.11/lib/python3.11/site-packages/sempy/_utils/_log.py:370, in mds_log.<locals>.get_wrapper.<locals>.log_decorator_wrapper(*args, **kwargs)
    367 start_time = time.perf_counter()
    369 try:
--> 370     result = func(*args, **kwargs)
    372     # The invocation for get_message_dict moves after the function
    373     # so it can access the state after the method call
    374     message.update(extractor.get_completion_message_dict(result, arg_dict))

File ~/jupyter-env/python3.11/lib/python3.11/site-packages/sempy_labs/lakehouse/_get_lakehouse_tables.py:114, in get_lakehouse_tables(lakehouse, workspace, extended, count_rows, export, exclude_shortcuts)
    112 size_in_bytes = 0
    113 for f in latest_files:
--> 114     local_file_path = os.path.join(
    115         local_path, "Tables", schema_name, table_name, f
    116     )
    118     if os.path.exists(local_file_path):
    119         size_in_bytes += os.path.getsize(local_file_path)

File ~/jupyter-env/python3.11/lib/python3.11/posixpath.py:90, in join(a, *p)
     88             path += sep + b
     89 except (TypeError, AttributeError, BytesWarning):
---> 90     genericpath._check_arg_types('join', a, *p)
     91     raise
     92 return path

File ~/jupyter-env/python3.11/lib/python3.11/genericpath.py:152, in _check_arg_types(funcname, *args)
    150         hasbytes = True
    151     else:
--> 152         raise TypeError(f'{funcname}() argument must be str, bytes, or '
    153                         f'os.PathLike object, not {s.__class__.__name__!r}') from None
    154 if hasstr and hasbytes:
    155     raise TypeError("Can't mix strings and bytes in path components") from None

TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
````

Let me know if you would like me to put this in a new issue (or two).

**Comment by m-kovalsky** [comment]
Thanks for the detailed response. It will help a lot. I will look into the issue when I have a moment. In the meantime it is recommended to read this:

https://github.com/microsoft/semantic-link-labs/wiki/Frequently-Asked-Questions-(FAQ)#should-i-use-pip-install-or-pip-install

**Comment by philosophicles** [comment]
Thanks @m-kovalsky , as always, really appreciate your work on this project :-D

Total side-track here, but re `!pip` vs `%pip`, the FAQ you link to seems at odds with the official MSFT docs: 

https://learn.microsoft.com/en-us/fabric/data-engineering/using-python-experience-on-notebook#:~:text=In%20Python%20Notebook%2C%20%25pip%20and%20!pip%20have%20the%20same%20behavior

There is nothing in the official docs indicating that we should not use `!pip`, the message appears to be "ehhh take your pick". I appreciate this GitHub project is owned by Microsoft so your FAQ is not exactly _un_official, but I feel like learn.microsoft.com is regarded as "the" trusted source above all others?

**Comment by m-kovalsky** [comment]
@philosophicles would you please try the get_lakehouse_tables function in this [PR](https://github.com/microsoft/semantic-link-labs/pull/1077)?

**Comment by m-kovalsky** [comment]
Thanks for sharing the documentation. I don't think they have the same behavior in a notebook. There have been numerous weird issues which have been resolved by people using %pip instead of !pip. I've always used %pip and have never had any issues.

**Comment by philosophicles** [comment]
Ok, I have !pip working fine in a fair number of production notebooks, but I'll take that on board and phase it out.

I'll test the PR tomorrow, Monday, and let you know. Thanks!

**Comment by philosophicles** [comment]
In context of **error type 1 (pandas KeyError)**, from this call: 

`l.get_lakehouse_tables('empty_lakehouse_no_schemas', count_rows=True)`

I'm still getting KeyError but with a different traceback: 

````
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/jupyter-env/python3.11/lib/python3.11/site-packages/pandas/core/indexes/base.py:3791, in Index.get_loc(self, key)
   3790 try:
-> 3791     return self._engine.get_loc(casted_key)
   3792 except KeyError as err:

File index.pyx:152, in pandas._libs.index.IndexEngine.get_loc()

File index.pyx:181, in pandas._libs.index.IndexEngine.get_loc()

File pandas/_libs/hashtable_class_helper.pxi:7080, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas/_libs/hashtable_class_helper.pxi:7088, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'Row Count'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Cell In[14], line 1
----> 1 l.get_lakehouse_tables('empty_lakehouse_no_schemas', count_rows=True)

File ~/jupyter-env/python3.11/lib/python3.11/site-packages/sempy/_utils/_log.py:370, in mds_log.<locals>.get_wrapper.<locals>.log_decorator_wrapper(*args, **kwargs)
    367 start_time = time.perf_counter()
    369 try:
--> 370     result = func(*args, **kwargs)
    372     # The invocation for get_message_dict moves after the function
    373     # so it can access the state after the method call
    374     message.update(extractor.get_completion_message_dict(result, arg_dict))

File ~/jupyter-env/python3.11/lib/python3.11/site-packages/sempy_labs/lakehouse/_get_lakehouse_tables.py:187, in get_lakehouse_tables(lakehouse, workspace, extended, count_rows, export, exclude_shortcuts)
    184 if count_rows:
    185     if _pure_python_notebook:
    186         df["Row Count"] = (
--> 187             df["Row Count"]
    188             .map(lambda x: x.as_py() if hasattr(x, "as_py") else x)
    189             .astype("Int64")
    190         )
    191     else:
    192         df["Row Count"] = df["Row Count"].astype(int)

File ~/jupyter-env/python3.11/lib/python3.11/site-packages/pandas/core/frame.py:3893, in DataFrame.__getitem__(self, key)
   3891 if self.columns.nlevels > 1:
   3892     return self._getitem_multilevel(key)
-> 3893 indexer = self.columns.get_loc(key)
   3894 if is_integer(indexer):
   3895     indexer = [indexer]

File ~/jupyter-env/python3.11/lib/python3.11/site-packages/pandas/core/indexes/base.py:3798, in Index.get_loc(self, key)
   3793     if isinstance(casted_key, slice) or (
   3794         isinstance(casted_key, abc.Iterable)
   3795         and any(isinstance(x, slice) for x in casted_key)
   3796     ):
   3797         raise InvalidIndexError(key)
-> 3798     raise KeyError(key) from err
   3799 except TypeError:
   3800     # If we have a listlike key, _check_indexing_error will raise
   3801     #  InvalidIndexError. Otherwise we fall through and re-raise
   3802     #  the TypeError.
   3803     self._check_indexing_error(key)

KeyError: 'Row Count'
````

I notice on line 185 you're doing `if _pure_python_notebook:` rather than `if _pure_python_notebook**()**:`.

Not sure that's the whole problem though as we'd still be going down the same `if True` code path with or without the parentheses... it looks like the previous assignment of row_count in the line 159-165 block isn't happening but I can't work out why that is.

**Comment by philosophicles** [comment]
Error message 2 (os join() TypeError) appears unchanged. Looking at the diff in the PR, I notice you've changed how the `table_path` variable is assigned around line 130, but the error is happening earlier (line 114) with the assignment of `local_file_path`.

**Comment by m-kovalsky** [comment]
@philosophicles made 2 fixes in the PR for this. Would you please check.

**Comment by philosophicles** [comment]
@m-kovalsky  that's fixed both error types now.

The simple test matrix I included before is now effectively all green ✅✅✅.

**Comment by m-kovalsky** [comment]
Fixed in [0.13.2](https://github.com/microsoft/semantic-link-labs/releases/tag/0.13.2)
